/**
 * Image-generation support catalog — ported verbatim from the Cherry Studio v2
 * provider registry (`data/models.json` creator blocks + `data/provider-models.json`
 * provider overrides). "fork 缝": a static TS data module standing in for the v2
 * `@cherrystudio/provider-registry` package, per the fork's no-extra-package rule.
 *
 * SCOPE — the OpenAI-compatible plane only (`POST {apiHost}/v1/images/generations`).
 * Modes declaring a `vendorTransport` (dashscope / ppio / aihubmix / tokenhub /
 * minimax / ollama / google / bytedance) are deliberately ABSENT: this plane cannot
 * serve them, so the painting path raises an explicit `UNSUPPORTED_VENDOR` error
 * instead of silently dropping the parameters.
 *
 * PROVENANCE: every entry below carries the v2 source file + line of the model's
 * `id:`/`modelId:` field, so each support block is traceable to its origin.
 *
 * GENERATED by `tools/v2-img-extract/gen-catalog.js` (then Biome-formatted) —
 * regenerate with that script; do not hand-edit.
 */

/** v2 `CANONICAL_PARAM_KEY` — the closed canonical vocabulary (all 44 keys). */
export const CANONICAL_PARAM_KEYS = [
  'addWatermark',
  'aspectRatio',
  'background',
  'bottomScale',
  'cfg',
  'customSize',
  'detail',
  'enableInterleave',
  'function',
  'guidanceScale',
  'imageResolution',
  'imageWeight',
  'isSketch',
  'leftScale',
  'magicPromptOption',
  'maxImages',
  'moderation',
  'negativePrompt',
  'numImages',
  'numInferenceSteps',
  'outputFormat',
  'outputCompression',
  'personGeneration',
  'promptEnhancement',
  'promptExtend',
  'quality',
  'resolution',
  'refMode',
  'refStrength',
  'renderingSpeed',
  'resemblance',
  'rightScale',
  'safetyTolerance',
  'seed',
  'sequentialImageGeneration',
  'size',
  'sourceLang',
  'strength',
  'style',
  'styleType',
  'targetLang',
  'thinkingMode',
  'topScale',
  'upscaleFactor'
] as const

export type CanonicalParamKey = (typeof CANONICAL_PARAM_KEYS)[number]

export type ImageGenerationMode = 'generate' | 'edit' | 'remix' | 'upscale' | 'merge'

/** v2 `SupportSpecSchema` — the widget arm plus its per-model constraints. */
export type SupportSpec =
  | { type: 'switch'; default?: boolean }
  | { type: 'enum'; options: string[]; default?: string; render?: 'select' | 'chips'; columns?: number }
  | { type: 'range'; min: number; max: number; default?: number; step?: number }
  | { type: 'size'; minSide: number; maxSide: number; pairedEnumKey?: string }
  | { type: 'text'; multiline?: boolean }

/** v2 `IMAGE_PARAM_CATALOG` value kinds — the coercion arm per canonical key. */
export type CanonicalParamKind = 'string' | 'bool' | 'number' | 'int'

/** v2 `IMAGE_PARAM_CATALOG` (imageParamCatalog.ts:45-90), kind only. */
export const CANONICAL_PARAM_KINDS: Record<CanonicalParamKey, CanonicalParamKind> = {
  addWatermark: 'bool',
  aspectRatio: 'string',
  background: 'string',
  bottomScale: 'number',
  cfg: 'number',
  customSize: 'string',
  detail: 'number',
  enableInterleave: 'bool',
  function: 'string',
  guidanceScale: 'number',
  imageResolution: 'string',
  imageWeight: 'number',
  isSketch: 'bool',
  leftScale: 'number',
  magicPromptOption: 'bool',
  maxImages: 'int',
  moderation: 'string',
  negativePrompt: 'string',
  numImages: 'int',
  numInferenceSteps: 'int',
  outputFormat: 'string',
  outputCompression: 'int',
  personGeneration: 'string',
  promptEnhancement: 'bool',
  promptExtend: 'bool',
  quality: 'string',
  resolution: 'string',
  refMode: 'string',
  refStrength: 'number',
  renderingSpeed: 'string',
  resemblance: 'number',
  rightScale: 'number',
  safetyTolerance: 'int',
  seed: 'int',
  sequentialImageGeneration: 'string',
  size: 'string',
  sourceLang: 'string',
  strength: 'number',
  style: 'string',
  styleType: 'string',
  targetLang: 'string',
  thinkingMode: 'bool',
  topScale: 'number',
  upscaleFactor: 'number'
}

/** v2 `ImageModeDefSchema`, minus the v2-only transport/limit fields. */
export interface ImageModeDef {
  supports: Partial<Record<CanonicalParamKey, SupportSpec>>
  /** v2 `requirePrompt`: `false` skips the generic non-empty-prompt check. */
  requirePrompt?: boolean
}

/** v2 `ImageGenerationSupportSchema`. */
export interface ImageGenerationSupport {
  modes: Partial<Record<ImageGenerationMode, ImageModeDef>>
}

/** One ported (owner, modelId) support block with its v2 provenance. */
export interface ImageGenerationCatalogEntry {
  /** v2 provider id (override) or creator id (creator default). */
  owner: string
  modelId: string
  provenance: {
    /** Explicit per-(provider, model) override wins over the creator default. */
    source: 'provider' | 'creator'
    file: string
    line?: number
    /** Set when the v2 block is pipeline-generated (no hand-written override). */
    note?: string
  }
  support: ImageGenerationSupport
}

const MODE_ORDER: readonly ImageGenerationMode[] = ['generate', 'edit', 'remix', 'upscale', 'merge']

/** The support-spec index a single mode table row points at. */
type ModeSupportTable = Partial<Record<ImageGenerationMode, Record<string, number>>>

/** v2 `ModeDef.requirePrompt` per mode (absent = the default, prompt required). */
const REQUIRE_PROMPT: Partial<Record<string, Partial<Record<ImageGenerationMode, boolean>>>> = {}

// ── Deduplicated support specs (index = the comment above each line) ─────────

const SUPPORT_SPECS: readonly SupportSpec[] = [
  { default: 1, max: 1, min: 1, type: 'range' }, // 0
  {
    default: '1664x928',
    options: ['1664x928', '1472x1140', '1328x1328', '1140x1472', '928x1664'],
    render: 'chips',
    type: 'enum'
  }, // 1
  { multiline: true, type: 'text' }, // 2
  { default: 1, max: 6, min: 1, type: 'range' }, // 3
  { type: 'text' }, // 4
  {
    default: 'auto',
    options: ['auto', '1328x1328', '1664x928', '928x1664', '1472x1140', '1140x1472'],
    render: 'chips',
    type: 'enum'
  }, // 5
  { type: 'switch' }, // 6
  { options: ['jpeg', 'png', 'webp'], type: 'enum' }, // 7
  { default: '1K', options: ['1K', '2K'], render: 'chips', type: 'enum' }, // 8
  { default: true, type: 'switch' }, // 9
  { default: '2K', options: ['1K', '2K', '4K'], render: 'chips', type: 'enum' }, // 10
  {
    default: 'ASPECT_1_1',
    options: ['ASPECT_1_1', 'ASPECT_4_3', 'ASPECT_3_4', 'ASPECT_16_9', 'ASPECT_9_16', 'ASPECT_21_9', 'ASPECT_9_21'],
    render: 'chips',
    type: 'enum'
  }, // 11
  { default: 2, max: 6, min: 0, type: 'range' }, // 12
  { default: 1, max: 10, min: 1, type: 'range' }, // 13
  { default: '1024x1024', options: ['256x256', '512x512', '1024x1024'], render: 'chips', type: 'enum' }, // 14
  { options: ['standard', 'hd'], type: 'enum' }, // 15
  { default: '1024x1024', options: ['1024x1024', '1792x1024', '1024x1792'], render: 'chips', type: 'enum' }, // 16
  { options: ['vivid', 'natural'], type: 'enum' }, // 17
  { options: ['auto', 'transparent', 'opaque'], type: 'enum' }, // 18
  { options: ['auto', 'low'], type: 'enum' }, // 19
  { options: ['auto', 'low', 'medium', 'high'], type: 'enum' }, // 20
  { default: '1024x1024', options: ['auto', '1024x1024', '1536x1024', '1024x1536'], render: 'chips', type: 'enum' }, // 21
  { options: ['auto', 'opaque'], type: 'enum' }, // 22
  { default: '1:1', options: ['1:1', '4:3', '3:4', '16:9', '9:16'], render: 'chips', type: 'enum' }, // 23
  {
    default: '1024x1024',
    options: ['1024x1024', '768x1344', '864x1152', '1344x768', '1152x864', '1440x720', '720x1440'],
    render: 'chips',
    type: 'enum'
  }, // 24
  {
    default: '1280x1280',
    options: ['1280x1280', '1568x1056', '1056x1568', '1472x1088', '1088x1472', '1728x960', '960x1728'],
    render: 'chips',
    type: 'enum'
  }, // 25
  {
    default: '2048x2048',
    options: ['2048x2048', '2304x1728', '1728x2304', '2560x1440', '1440x2560', '2496x1664', '1664x2496', '3024x1296'],
    render: 'chips',
    type: 'enum'
  }, // 26
  { default: 1, max: 15, min: 1, type: 'range' }, // 27
  { options: ['png', 'jpeg'], type: 'enum' }, // 28
  { default: 'disabled', options: ['auto', 'disabled'], type: 'enum' }, // 29
  { default: '2K', options: ['2K', '3K', '2048x2048'], render: 'chips', type: 'enum' }, // 30
  { default: '1x1', options: ['1x1'], render: 'chips', type: 'enum' }, // 31
  { default: '1:1', options: ['1:1', '9:16', '16:9', '3:4', '4:3', '2:3', '3:2'], render: 'chips', type: 'enum' }, // 32
  { default: '1K', options: ['1K', '2K', '4K'], render: 'chips', type: 'enum' }, // 33
  { options: ['png', 'jpeg', 'webp'], type: 'enum' }, // 34
  {
    default: '1024x1024',
    options: ['1024x1024', '1152x864', '864x1152', '1664x928', '928x1664'],
    render: 'chips',
    type: 'enum'
  }, // 35
  { default: '1:1', options: ['1:1', '16:9', '9:16', '4:3', '3:4', '1x1'], render: 'chips', type: 'enum' }, // 36
  { default: '1:1', options: ['1:1', '16:9', '9:16', '4:3', '3:4'], render: 'chips', type: 'enum' }, // 37
  { default: 1, max: 4, min: 1, type: 'range' }, // 38
  {
    default: '1328x1328',
    options: ['1664x928', '1472x1140', '1328x1328', '1140x1472', '928x1664'],
    render: 'chips',
    type: 'enum'
  }, // 39
  { default: false, type: 'switch' }, // 40
  {
    default: '1280x1280',
    options: ['1280x1280', '1664x928', '928x1664', '1472x1140', '1140x1472'],
    render: 'chips',
    type: 'enum'
  }, // 41
  { options: ['1:1', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '21:9', 'auto'], type: 'enum' }, // 42
  { max: 1, min: 1, step: 1, type: 'range' }, // 43
  { options: ['1:1', '2:3', '3:2', '3:4', '4:3', '4:5', '5:4', '9:16', '16:9', '21:9'], type: 'enum' }, // 44
  {
    options: ['1:1', '1:4', '1:8', '2:3', '3:2', '3:4', '4:1', '4:3', '4:5', '5:4', '8:1', '9:16', '16:9', '21:9'],
    type: 'enum'
  }, // 45
  { options: ['512', '1K', '2K', '4K'], type: 'enum' }, // 46
  { options: ['1K'], type: 'enum' }, // 47
  { options: ['1K', '2K', '4K'], type: 'enum' }, // 48
  { options: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9', 'auto'], type: 'enum' }, // 49
  { max: 10, min: 1, step: 1, type: 'range' }, // 50
  { options: ['1:1', '3:2', '2:3', 'auto'], type: 'enum' }, // 51
  {
    options: [
      '1:1',
      '3:4',
      '4:3',
      '9:16',
      '16:9',
      '2:3',
      '3:2',
      '9:19.5',
      '19.5:9',
      '9:20',
      '20:9',
      '1:2',
      '2:1',
      'auto'
    ],
    type: 'enum'
  }, // 52
  { options: ['low', 'medium'], type: 'enum' }, // 53
  { options: ['1K', '2K'], type: 'enum' }, // 54
  { options: ['1:1', '4:3', '3:2', '16:9', '4:5', '2:3', '9:16'], type: 'enum' }, // 55
  { options: ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3', 'auto'], type: 'enum' }, // 56
  {
    options: ['1:1', '1:2', '1:4', '2:1', '2:3', '3:2', '3:4', '4:1', '4:3', '4:5', '5:4', '9:16', '16:9'],
    type: 'enum'
  }, // 57
  { max: 6, min: 1, step: 1, type: 'range' }, // 58
  { options: ['1:1', '4:3', '3:4', '16:9', '9:16', 'auto'], type: 'enum' }, // 59
  { options: ['svg'], type: 'enum' }, // 60
  { options: ['jpeg'], type: 'enum' }, // 61
  {
    options: [
      '1:1',
      '1:2',
      '2:1',
      '2:3',
      '3:2',
      '3:4',
      '4:3',
      '4:5',
      '5:4',
      '9:16',
      '16:9',
      '9:19.5',
      '19.5:9',
      '9:20',
      '20:9',
      '9:21',
      '21:9',
      'auto'
    ],
    type: 'enum'
  }, // 62
  { max: 4, min: 1, step: 1, type: 'range' }, // 63
  { options: ['2K', '4K'], type: 'enum' } // 64
]

function toSupport(key: string, table: Record<string, Record<string, number>>): ImageGenerationSupport {
  const modes: ImageGenerationSupport['modes'] = {}
  const promptFlags = REQUIRE_PROMPT[key] ?? {}
  for (const mode of MODE_ORDER) {
    const indices = table[mode]
    if (!indices) continue
    const supports: Partial<Record<CanonicalParamKey, SupportSpec>> = {}
    for (const [supportKey, index] of Object.entries(indices)) {
      supports[supportKey as CanonicalParamKey] = SUPPORT_SPECS[index]
    }
    modes[mode] = { supports, ...(promptFlags[mode] !== undefined && { requirePrompt: promptFlags[mode] }) }
  }
  return { modes }
}

// ── Provider overrides — v2 `provider-models.json` (override wins) ───────────

const PROVIDER_SUPPORTS: Record<string, ModeSupportTable> = {
  'dmxapi/dall-e-3': {
    generate: { numImages: 0, quality: 15, size: 16, style: 17 }
  }, // packages/provider-registry/src/providers/dmxapi.ts:106
  'dmxapi/doubao-seedream-4-0': {
    generate: { numImages: 0, size: 26 },
    edit: { numImages: 0, size: 26 },
    merge: { numImages: 0, size: 26 }
  }, // packages/provider-registry/src/providers/dmxapi.ts:112
  'dmxapi/doubao-seedream-4-5': {
    generate: { numImages: 0, size: 26 },
    edit: { numImages: 0, size: 26 },
    merge: { numImages: 0, size: 26 }
  }, // packages/provider-registry/src/providers/dmxapi.ts:118
  'dmxapi/gemini-2-5-flash-image': {
    generate: { numImages: 0, size: 31 },
    edit: { numImages: 0, size: 31 },
    merge: { numImages: 0, size: 31 }
  }, // packages/provider-registry/src/providers/dmxapi.ts:232
  'dmxapi/gpt-image-1-5': {
    generate: { background: 18, moderation: 19, numImages: 13, outputFormat: 34, quality: 20, size: 21 }
  }, // packages/provider-registry/src/providers/dmxapi.ts:185
  'dmxapi/musesteamer-air-image': {
    generate: { numImages: 0, size: 35 }
  }, // packages/provider-registry/src/providers/dmxapi.ts:239
  'dmxapi/nano-banana': {
    generate: { aspectRatio: 36, numImages: 0 },
    edit: { aspectRatio: 36, numImages: 0 },
    merge: { aspectRatio: 36, numImages: 0 }
  }, // packages/provider-registry/src/providers/dmxapi.ts:261
  'dmxapi/nano-banana-2': {
    edit: { aspectRatio: 37, numImages: 0 },
    merge: { aspectRatio: 37, numImages: 0 }
  }, // packages/provider-registry/src/providers/dmxapi.ts:271
  'openrouter/flux-2-flex': {
    generate: { aspectRatio: 42, numImages: 43, outputFormat: 28, seed: 4 },
    edit: { aspectRatio: 42, numImages: 43, outputFormat: 28, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/flux-2-klein-4b': {
    generate: { aspectRatio: 42, numImages: 43, outputFormat: 28, seed: 4 },
    edit: { aspectRatio: 42, numImages: 43, outputFormat: 28, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/flux-2-max': {
    generate: { aspectRatio: 42, numImages: 43, outputFormat: 28, seed: 4 },
    edit: { aspectRatio: 42, numImages: 43, outputFormat: 28, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/flux-2-pro': {
    generate: { aspectRatio: 42, numImages: 43, outputFormat: 28, seed: 4 },
    edit: { aspectRatio: 42, numImages: 43, outputFormat: 28, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gemini-2-5-flash-image': {
    generate: { aspectRatio: 44, numImages: 43 },
    edit: { aspectRatio: 44, numImages: 43 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gemini-3-1-flash-image': {
    generate: { aspectRatio: 45, numImages: 43, resolution: 46 },
    edit: { aspectRatio: 45, numImages: 43, resolution: 46 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gemini-3-1-flash-image-preview': {
    generate: { aspectRatio: 45, numImages: 43, resolution: 46 },
    edit: { aspectRatio: 45, numImages: 43, resolution: 46 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gemini-3-1-flash-lite-image': {
    generate: { aspectRatio: 45, numImages: 43, resolution: 47 },
    edit: { aspectRatio: 45, numImages: 43, resolution: 47 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gemini-3-pro-image': {
    generate: { aspectRatio: 44, numImages: 43, resolution: 48 },
    edit: { aspectRatio: 44, numImages: 43, resolution: 48 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gemini-3-pro-image-preview': {
    generate: { aspectRatio: 44, numImages: 43, resolution: 48 },
    edit: { aspectRatio: 44, numImages: 43, resolution: 48 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gpt-5-4-image-2': {
    generate: { aspectRatio: 49, background: 22, numImages: 50, quality: 20 },
    edit: { aspectRatio: 49, background: 22, numImages: 50, quality: 20 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gpt-5-image': {
    generate: { aspectRatio: 51, background: 18, numImages: 50, quality: 20 },
    edit: { aspectRatio: 51, background: 18, numImages: 50, quality: 20 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gpt-5-image-mini': {
    generate: { aspectRatio: 51, background: 18, numImages: 50, quality: 20 },
    edit: { aspectRatio: 51, background: 18, numImages: 50, quality: 20 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gpt-image-1': {
    generate: { aspectRatio: 51, background: 18, numImages: 50, quality: 20 },
    edit: { aspectRatio: 51, background: 18, numImages: 50, quality: 20 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gpt-image-1-mini': {
    generate: { aspectRatio: 51, background: 18, numImages: 50, quality: 20 },
    edit: { aspectRatio: 51, background: 18, numImages: 50, quality: 20 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/gpt-image-2': {
    generate: { aspectRatio: 49, background: 22, numImages: 50, quality: 20 },
    edit: { aspectRatio: 49, background: 22, numImages: 50, quality: 20 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/grok-imagine-image-2-0': {
    generate: { aspectRatio: 52, numImages: 43, quality: 53, resolution: 54 },
    edit: { aspectRatio: 52, numImages: 43, quality: 53, resolution: 54 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/grok-imagine-image-quality': {
    generate: { aspectRatio: 52, numImages: 43, resolution: 54 },
    edit: { aspectRatio: 52, numImages: 43, resolution: 54 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/krea-2-large': {
    generate: { aspectRatio: 55, resolution: 47, seed: 4 },
    edit: { aspectRatio: 55, resolution: 47, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/krea-2-medium': {
    generate: { aspectRatio: 55, resolution: 47, seed: 4 },
    edit: { aspectRatio: 55, resolution: 47, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/krea-2-medium-turbo': {
    generate: { aspectRatio: 55, resolution: 47, seed: 4 },
    edit: { aspectRatio: 55, resolution: 47, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/mai-image-2-5': {
    generate: { aspectRatio: 56, numImages: 43 },
    edit: { aspectRatio: 56, numImages: 43 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/mai-image-2-5-pro': {
    generate: { aspectRatio: 56, numImages: 43 },
    edit: { aspectRatio: 56, numImages: 43 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/qwen-image-3': {
    generate: { aspectRatio: 57, numImages: 58, resolution: 54, seed: 4 },
    edit: { aspectRatio: 57, numImages: 58, resolution: 54, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/qwen-image-3-pro': {
    generate: { aspectRatio: 57, numImages: 58, resolution: 54, seed: 4 },
    edit: { aspectRatio: 57, numImages: 58, resolution: 54, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v3': {
    generate: { aspectRatio: 59, numImages: 58 },
    edit: { aspectRatio: 59, numImages: 58 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4': {
    generate: { aspectRatio: 59, numImages: 58 },
    edit: { aspectRatio: 59, numImages: 58 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4-1': {
    generate: { aspectRatio: 59, numImages: 58 },
    edit: { aspectRatio: 59, numImages: 58 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4-1-pro': {
    generate: { aspectRatio: 59, numImages: 58 },
    edit: { aspectRatio: 59, numImages: 58 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4-1-pro-vector': {
    generate: { aspectRatio: 59, numImages: 58, outputFormat: 60 },
    edit: { aspectRatio: 59, numImages: 58, outputFormat: 60 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4-1-utility': {
    generate: { aspectRatio: 59, numImages: 58 },
    edit: { aspectRatio: 59, numImages: 58 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4-1-utility-pro': {
    generate: { aspectRatio: 59, numImages: 58 },
    edit: { aspectRatio: 59, numImages: 58 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4-1-vector': {
    generate: { aspectRatio: 59, numImages: 58, outputFormat: 60 },
    edit: { aspectRatio: 59, numImages: 58, outputFormat: 60 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4-pro': {
    generate: { aspectRatio: 59, numImages: 58 },
    edit: { aspectRatio: 59, numImages: 58 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4-pro-vector': {
    generate: { aspectRatio: 59, numImages: 58, outputFormat: 60 },
    edit: { aspectRatio: 59, numImages: 58, outputFormat: 60 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/recraft-v4-vector': {
    generate: { aspectRatio: 59, numImages: 58, outputFormat: 60 },
    edit: { aspectRatio: 59, numImages: 58, outputFormat: 60 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/riverflow-v2-5-fast': {
    generate: { aspectRatio: 42, background: 22, numImages: 43, outputFormat: 61, resolution: 54 },
    edit: { aspectRatio: 42, background: 22, numImages: 43, outputFormat: 61, resolution: 54 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/riverflow-v2-5-pro': {
    generate: { aspectRatio: 42, background: 18, numImages: 43, outputFormat: 34, resolution: 48 },
    edit: { aspectRatio: 42, background: 18, numImages: 43, outputFormat: 34, resolution: 48 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/riverflow-v2-fast': {
    generate: { aspectRatio: 42, numImages: 43, resolution: 48 },
    edit: { aspectRatio: 42, numImages: 43, resolution: 48 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/riverflow-v2-pro': {
    generate: { aspectRatio: 42, numImages: 43, resolution: 48 },
    edit: { aspectRatio: 42, numImages: 43, resolution: 48 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/seedream-4-5': {
    generate: { aspectRatio: 62, numImages: 50, resolution: 48, seed: 4 },
    edit: { aspectRatio: 62, numImages: 50, resolution: 48, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/seedream-5-0-lite': {
    generate: { aspectRatio: 62, numImages: 63, resolution: 64, seed: 4 },
    edit: { aspectRatio: 62, numImages: 63, resolution: 64, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'openrouter/seedream-5-0-pro': {
    generate: { aspectRatio: 62, numImages: 43, resolution: 54, seed: 4 },
    edit: { aspectRatio: 62, numImages: 43, resolution: 54, seed: 4 }
  }, // packages/provider-registry/src/providers/openrouter.ts (generated)
  'zhipu/cogview-4': {
    generate: { addWatermark: 6, numImages: 0, quality: 15, size: 24 }
  }, // packages/provider-registry/src/providers/zhipu.ts:84
  'zhipu/glm-image': {
    generate: { addWatermark: 6, numImages: 0, quality: 15, size: 25 }
  } // packages/provider-registry/src/providers/zhipu.ts:105
}

// ── Creator defaults — v2 `models.json` ─────────────────────────────────────

const CREATOR_SUPPORTS: Record<string, ModeSupportTable> = {
  'alibaba/qwen-image': {
    generate: { numImages: 0, size: 1 }
  }, // packages/provider-registry/src/creators/alibaba.ts:103
  'alibaba/qwen-image-3-0': {
    generate: { negativePrompt: 2, numImages: 3, seed: 4, size: 5 },
    edit: { negativePrompt: 2, numImages: 3, seed: 4, size: 5 }
  }, // packages/provider-registry/src/creators/alibaba.ts:131
  'alibaba/qwen-image-3-0-pro': {
    generate: { negativePrompt: 2, numImages: 3, seed: 4, size: 5 },
    edit: { negativePrompt: 2, numImages: 3, seed: 4, size: 5 }
  }, // packages/provider-registry/src/creators/alibaba.ts:145
  'alibaba/qwen-image-edit': {
    edit: { addWatermark: 6, outputFormat: 7, seed: 4 }
  }, // packages/provider-registry/src/creators/alibaba.ts:159
  'alibaba/wan2-6-image': {
    generate: { addWatermark: 6, imageResolution: 8, negativePrompt: 2, promptExtend: 9, seed: 4 }
  }, // packages/provider-registry/src/creators/alibaba.ts:185
  'alibaba/wan2-6-t2i': {
    generate: { addWatermark: 6, imageResolution: 8, negativePrompt: 2, promptExtend: 9, seed: 4 }
  }, // packages/provider-registry/src/creators/alibaba.ts:281
  'alibaba/wan2-7-image': {
    generate: { addWatermark: 6, imageResolution: 8, seed: 4, thinkingMode: 9 }
  }, // packages/provider-registry/src/creators/alibaba.ts:219
  'alibaba/wan2-7-image-pro': {
    generate: { addWatermark: 6, imageResolution: 10, seed: 4, thinkingMode: 9 }
  }, // packages/provider-registry/src/creators/alibaba.ts:250
  'black-forest-labs/flux-2-flex': {
    generate: { aspectRatio: 11, safetyTolerance: 12, seed: 4 }
  }, // packages/provider-registry/src/creators/black-forest-labs.ts:171
  'black-forest-labs/flux-2-pro': {
    generate: { aspectRatio: 11, safetyTolerance: 12, seed: 4 }
  }, // packages/provider-registry/src/creators/black-forest-labs.ts:132
  'black-forest-labs/flux-kontext-max': {
    edit: { aspectRatio: 11, safetyTolerance: 12, seed: 4 }
  }, // packages/provider-registry/src/creators/black-forest-labs.ts:93
  'black-forest-labs/flux-kontext-pro': {
    edit: { aspectRatio: 11, safetyTolerance: 12, seed: 4 }
  }, // packages/provider-registry/src/creators/black-forest-labs.ts:54
  'openai/dall-e-2': {
    generate: { numImages: 13, size: 14 }
  }, // packages/provider-registry/src/creators/openai.ts:150
  'openai/dall-e-3': {
    generate: { quality: 15, size: 16, style: 17 }
  }, // packages/provider-registry/src/creators/openai.ts:120
  'openai/gpt-image-1': {
    generate: { background: 18, moderation: 19, numImages: 13, quality: 20, size: 21 },
    edit: { background: 18, moderation: 19, numImages: 13, quality: 20, size: 21 }
  }, // packages/provider-registry/src/creators/openai.ts:213
  'openai/gpt-image-1-mini': {
    generate: { background: 18, moderation: 19, numImages: 13, quality: 20, size: 21 },
    edit: { background: 18, moderation: 19, numImages: 13, quality: 20, size: 21 }
  }, // packages/provider-registry/src/creators/openai.ts:52
  'openai/gpt-image-2': {
    generate: { background: 22, numImages: 13, quality: 20, size: 21 }
  }, // packages/provider-registry/src/creators/openai.ts:177
  'tencent/hy-image-lite': {
    generate: { addWatermark: 6, aspectRatio: 23, seed: 4 }
  }, // packages/provider-registry/src/creators/tencent.ts:97
  'tencent/hy-image-v3-0': {
    generate: { addWatermark: 6, aspectRatio: 23, negativePrompt: 2, seed: 4 }
  }, // packages/provider-registry/src/creators/tencent.ts:73
  'zhipu/cogview-4': {
    generate: { negativePrompt: 2, numImages: 0, quality: 15, seed: 4, size: 24 }
  }, // packages/provider-registry/src/creators/zhipu.ts:63
  'zhipu/glm-image': {
    generate: { addWatermark: 6, size: 25 }
  } // packages/provider-registry/src/creators/zhipu.ts:105
}

const PROVIDER_PROVENANCE: Record<string, { file: string; line?: number; note?: string }> = {
  'dmxapi/dall-e-3': { file: 'packages/provider-registry/src/providers/dmxapi.ts', line: 106 },
  'dmxapi/doubao-seedream-4-0': { file: 'packages/provider-registry/src/providers/dmxapi.ts', line: 112 },
  'dmxapi/doubao-seedream-4-5': { file: 'packages/provider-registry/src/providers/dmxapi.ts', line: 118 },
  'dmxapi/gemini-2-5-flash-image': { file: 'packages/provider-registry/src/providers/dmxapi.ts', line: 232 },
  'dmxapi/gpt-image-1-5': { file: 'packages/provider-registry/src/providers/dmxapi.ts', line: 185 },
  'dmxapi/musesteamer-air-image': { file: 'packages/provider-registry/src/providers/dmxapi.ts', line: 239 },
  'dmxapi/nano-banana': { file: 'packages/provider-registry/src/providers/dmxapi.ts', line: 261 },
  'dmxapi/nano-banana-2': { file: 'packages/provider-registry/src/providers/dmxapi.ts', line: 271 },
  'openrouter/flux-2-flex': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "flux-2-flex")'
  },
  'openrouter/flux-2-klein-4b': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "flux-2-klein-4b")'
  },
  'openrouter/flux-2-max': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "flux-2-max")'
  },
  'openrouter/flux-2-pro': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "flux-2-pro")'
  },
  'openrouter/gemini-2-5-flash-image': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gemini-2-5-flash-image")'
  },
  'openrouter/gemini-3-1-flash-image': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gemini-3-1-flash-image")'
  },
  'openrouter/gemini-3-1-flash-image-preview': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gemini-3-1-flash-image-preview")'
  },
  'openrouter/gemini-3-1-flash-lite-image': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gemini-3-1-flash-lite-image")'
  },
  'openrouter/gemini-3-pro-image': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gemini-3-pro-image")'
  },
  'openrouter/gemini-3-pro-image-preview': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gemini-3-pro-image-preview")'
  },
  'openrouter/gpt-5-4-image-2': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gpt-5-4-image-2")'
  },
  'openrouter/gpt-5-image': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gpt-5-image")'
  },
  'openrouter/gpt-5-image-mini': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gpt-5-image-mini")'
  },
  'openrouter/gpt-image-1': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gpt-image-1")'
  },
  'openrouter/gpt-image-1-mini': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gpt-image-1-mini")'
  },
  'openrouter/gpt-image-2': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "gpt-image-2")'
  },
  'openrouter/grok-imagine-image-2-0': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "grok-imagine-image-2-0")'
  },
  'openrouter/grok-imagine-image-quality': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "grok-imagine-image-quality")'
  },
  'openrouter/krea-2-large': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "krea-2-large")'
  },
  'openrouter/krea-2-medium': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "krea-2-medium")'
  },
  'openrouter/krea-2-medium-turbo': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "krea-2-medium-turbo")'
  },
  'openrouter/mai-image-2-5': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "mai-image-2-5")'
  },
  'openrouter/mai-image-2-5-pro': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "mai-image-2-5-pro")'
  },
  'openrouter/qwen-image-3': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "qwen-image-3")'
  },
  'openrouter/qwen-image-3-pro': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "qwen-image-3-pro")'
  },
  'openrouter/recraft-v3': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v3")'
  },
  'openrouter/recraft-v4': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4")'
  },
  'openrouter/recraft-v4-1': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4-1")'
  },
  'openrouter/recraft-v4-1-pro': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4-1-pro")'
  },
  'openrouter/recraft-v4-1-pro-vector': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4-1-pro-vector")'
  },
  'openrouter/recraft-v4-1-utility': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4-1-utility")'
  },
  'openrouter/recraft-v4-1-utility-pro': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4-1-utility-pro")'
  },
  'openrouter/recraft-v4-1-vector': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4-1-vector")'
  },
  'openrouter/recraft-v4-pro': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4-pro")'
  },
  'openrouter/recraft-v4-pro-vector': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4-pro-vector")'
  },
  'openrouter/recraft-v4-vector': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "recraft-v4-vector")'
  },
  'openrouter/riverflow-v2-5-fast': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "riverflow-v2-5-fast")'
  },
  'openrouter/riverflow-v2-5-pro': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "riverflow-v2-5-pro")'
  },
  'openrouter/riverflow-v2-fast': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "riverflow-v2-fast")'
  },
  'openrouter/riverflow-v2-pro': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "riverflow-v2-pro")'
  },
  'openrouter/seedream-4-5': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "seedream-4-5")'
  },
  'openrouter/seedream-5-0-lite': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "seedream-5-0-lite")'
  },
  'openrouter/seedream-5-0-pro': {
    file: 'packages/provider-registry/src/providers/openrouter.ts',
    note: 'packages/provider-registry/src/providers/openrouter.ts is generated (no hand-written override): this block is enriched from OpenRouter\'s live image-models API into data/provider-models.json (override "seedream-5-0-pro")'
  },
  'zhipu/cogview-4': { file: 'packages/provider-registry/src/providers/zhipu.ts', line: 84 },
  'zhipu/glm-image': { file: 'packages/provider-registry/src/providers/zhipu.ts', line: 105 }
}

const CREATOR_PROVENANCE: Record<string, { file: string; line?: number; note?: string }> = {
  'alibaba/qwen-image': { file: 'packages/provider-registry/src/creators/alibaba.ts', line: 103 },
  'alibaba/qwen-image-3-0': { file: 'packages/provider-registry/src/creators/alibaba.ts', line: 131 },
  'alibaba/qwen-image-3-0-pro': { file: 'packages/provider-registry/src/creators/alibaba.ts', line: 145 },
  'alibaba/qwen-image-edit': { file: 'packages/provider-registry/src/creators/alibaba.ts', line: 159 },
  'alibaba/wan2-6-image': { file: 'packages/provider-registry/src/creators/alibaba.ts', line: 185 },
  'alibaba/wan2-6-t2i': { file: 'packages/provider-registry/src/creators/alibaba.ts', line: 281 },
  'alibaba/wan2-7-image': { file: 'packages/provider-registry/src/creators/alibaba.ts', line: 219 },
  'alibaba/wan2-7-image-pro': { file: 'packages/provider-registry/src/creators/alibaba.ts', line: 250 },
  'black-forest-labs/flux-2-flex': { file: 'packages/provider-registry/src/creators/black-forest-labs.ts', line: 171 },
  'black-forest-labs/flux-2-pro': { file: 'packages/provider-registry/src/creators/black-forest-labs.ts', line: 132 },
  'black-forest-labs/flux-kontext-max': {
    file: 'packages/provider-registry/src/creators/black-forest-labs.ts',
    line: 93
  },
  'black-forest-labs/flux-kontext-pro': {
    file: 'packages/provider-registry/src/creators/black-forest-labs.ts',
    line: 54
  },
  'openai/dall-e-2': { file: 'packages/provider-registry/src/creators/openai.ts', line: 150 },
  'openai/dall-e-3': { file: 'packages/provider-registry/src/creators/openai.ts', line: 120 },
  'openai/gpt-image-1': { file: 'packages/provider-registry/src/creators/openai.ts', line: 213 },
  'openai/gpt-image-1-mini': { file: 'packages/provider-registry/src/creators/openai.ts', line: 52 },
  'openai/gpt-image-2': { file: 'packages/provider-registry/src/creators/openai.ts', line: 177 },
  'tencent/hy-image-lite': { file: 'packages/provider-registry/src/creators/tencent.ts', line: 97 },
  'tencent/hy-image-v3-0': { file: 'packages/provider-registry/src/creators/tencent.ts', line: 73 },
  'zhipu/cogview-4': { file: 'packages/provider-registry/src/creators/zhipu.ts', line: 63 },
  'zhipu/glm-image': { file: 'packages/provider-registry/src/creators/zhipu.ts', line: 105 }
}

/** v2 override `apiModelId` aliases: catalog key → vendor wire id. */
const API_MODEL_ID_ALIASES: Record<string, string> = {
  'dmxapi/doubao-seedream-5-0-lite': 'doubao-seedream-5.0-lite',
  'dmxapi/gemini-2-5-flash-image': 'gemini-2.5-flash-image',
  'dmxapi/gemini-3-1-flash-image-preview': 'gemini-3.1-flash-image-preview',
  'dmxapi/gpt-image-1-5': 'gpt-image-1.5',
  'dmxapi/wan2-6-t2i': 'wan2.6-t2i',
  'openrouter/flux-2-flex': 'black-forest-labs/flux.2-flex',
  'openrouter/flux-2-klein-4b': 'black-forest-labs/flux.2-klein-4b',
  'openrouter/flux-2-max': 'black-forest-labs/flux.2-max',
  'openrouter/flux-2-pro': 'black-forest-labs/flux.2-pro',
  'openrouter/gemini-2-5-flash-image': 'google/gemini-2.5-flash-image',
  'openrouter/gemini-3-1-flash-image': 'google/gemini-3.1-flash-image',
  'openrouter/gemini-3-1-flash-image-preview': 'google/gemini-3.1-flash-image-preview',
  'openrouter/gemini-3-1-flash-lite-image': 'google/gemini-3.1-flash-lite-image',
  'openrouter/gemini-3-pro-image': 'google/gemini-3-pro-image',
  'openrouter/gemini-3-pro-image-preview': 'google/gemini-3-pro-image-preview',
  'openrouter/gpt-5-4-image-2': 'openai/gpt-5.4-image-2',
  'openrouter/gpt-5-image': 'openai/gpt-5-image',
  'openrouter/gpt-5-image-mini': 'openai/gpt-5-image-mini',
  'openrouter/gpt-image-1': 'openai/gpt-image-1',
  'openrouter/gpt-image-1-mini': 'openai/gpt-image-1-mini',
  'openrouter/gpt-image-2': 'openai/gpt-image-2',
  'openrouter/grok-imagine-image-2-0': 'x-ai/grok-imagine-image-2.0',
  'openrouter/grok-imagine-image-quality': 'x-ai/grok-imagine-image-quality',
  'openrouter/krea-2-large': 'krea/krea-2-large',
  'openrouter/krea-2-medium': 'krea/krea-2-medium',
  'openrouter/krea-2-medium-turbo': 'krea/krea-2-medium-turbo',
  'openrouter/mai-image-2-5': 'microsoft/mai-image-2.5',
  'openrouter/mai-image-2-5-pro': 'microsoft/mai-image-2.5-pro',
  'openrouter/qwen-image-3': 'qwen/qwen-image-3',
  'openrouter/qwen-image-3-pro': 'qwen/qwen-image-3-pro',
  'openrouter/recraft-v3': 'recraft/recraft-v3',
  'openrouter/recraft-v4': 'recraft/recraft-v4',
  'openrouter/recraft-v4-1': 'recraft/recraft-v4.1',
  'openrouter/recraft-v4-1-pro': 'recraft/recraft-v4.1-pro',
  'openrouter/recraft-v4-1-pro-vector': 'recraft/recraft-v4.1-pro-vector',
  'openrouter/recraft-v4-1-utility': 'recraft/recraft-v4.1-utility',
  'openrouter/recraft-v4-1-utility-pro': 'recraft/recraft-v4.1-utility-pro',
  'openrouter/recraft-v4-1-vector': 'recraft/recraft-v4.1-vector',
  'openrouter/recraft-v4-pro': 'recraft/recraft-v4-pro',
  'openrouter/recraft-v4-pro-vector': 'recraft/recraft-v4-pro-vector',
  'openrouter/recraft-v4-vector': 'recraft/recraft-v4-vector',
  'openrouter/riverflow-v2-5-fast': 'sourceful/riverflow-v2.5-fast',
  'openrouter/riverflow-v2-5-pro': 'sourceful/riverflow-v2.5-pro',
  'openrouter/riverflow-v2-fast': 'sourceful/riverflow-v2-fast',
  'openrouter/riverflow-v2-pro': 'sourceful/riverflow-v2-pro',
  'openrouter/seedream-4-5': 'bytedance-seed/seedream-4.5',
  'openrouter/seedream-5-0-lite': 'bytedance-seed/seedream-5-0-lite',
  'openrouter/seedream-5-0-pro': 'bytedance-seed/seedream-5-0-pro'
}

/**
 * Resolve the support block for a (provider, modelId) pair — the fork equivalent of
 * v2 `ProviderRegistryService.getImageGenerationSupport`, same resolution order:
 *
 *   1. the provider override (v2 `lookupModel` → `registryOverride.imageGeneration`)
 *   2. the creator default (v2 `presetModel.imageGeneration`)
 *   3. `null` — not on this plane; the caller must raise an explicit error.
 *
 * v2 override `apiModelId` aliases are indexed under BOTH spellings, because a fork
 * model id may carry either the catalog key or the vendor wire id.
 */
export function getImageGenerationSupport(
  providerId: string | undefined,
  modelId: string | undefined
): ImageGenerationSupport | null {
  const entry = getImageGenerationCatalogEntry(providerId, modelId)
  return entry ? entry.support : null
}

/** The catalog entry (support + provenance) for a pair, or `null`. */
export function getImageGenerationCatalogEntry(
  providerId: string | undefined,
  modelId: string | undefined
): ImageGenerationCatalogEntry | null {
  if (!providerId || !modelId) return null
  const providerTable = PROVIDER_SUPPORTS[providerId + '/' + modelId]
  if (providerTable) {
    return {
      owner: providerId,
      modelId,
      provenance: { source: 'provider', ...PROVIDER_PROVENANCE[providerId + '/' + modelId] },
      support: toSupport(providerId + '/' + modelId, providerTable)
    }
  }
  const creatorTable = CREATOR_SUPPORTS[providerId + '/' + modelId]
  if (creatorTable) {
    return {
      owner: providerId,
      modelId,
      provenance: { source: 'creator', ...CREATOR_PROVENANCE[providerId + '/' + modelId] },
      support: toSupport(providerId + '/' + modelId, creatorTable)
    }
  }
  const aliased = API_MODEL_ID_ALIASES[providerId + '/' + modelId]
  if (aliased !== undefined) return getImageGenerationCatalogEntry(providerId, aliased)
  return null
}

/** Every ported entry, for tests/inspection. */
export const IMAGE_GENERATION_CATALOG_ENTRIES: readonly ImageGenerationCatalogEntry[] = (
  [
    ...Object.keys(PROVIDER_SUPPORTS).map((key) => ({ key, source: 'provider' as const })),
    ...Object.keys(CREATOR_SUPPORTS).map((key) => ({ key, source: 'creator' as const }))
  ] as const
).map(({ key }) => {
  const slash = key.indexOf('/')
  const entry = getImageGenerationCatalogEntry(key.slice(0, slash), key.slice(slash + 1))
  if (!entry) throw new Error(`imageGenerationCatalog: unresolvable entry ${key}`)
  return entry
})

// ── Wire mapping (fork 缝) ──────────────────────────────────────────────────
//
// v2 splits this across three files: `imageParamCatalog.wireName` (the canonical →
// snake_case rename + the `wire` overrides), `AI_SDK_NATIVE_BINDINGS` (the four
// fields the AI SDK consumes as typed options) and `wireProfile.ts` (the per-provider
// `forward` / `fields` body map + `WIRE_REGISTRY`). The fork posts ONE flat JSON body
// to `/v1/images/generations`, so the three collapse here into: native binding →
// `option`, else profile `to`/`contribute`, else `wireName(key)`.
//
// Providers ABSENT from `IMAGE_WIRE_PROFILES` are off this plane: the main process
// refuses the request with an explicit `UNSUPPORTED_VENDOR` error rather than
// forwarding a body the vendor cannot read.

/** `camelCase` → `snake_case` (v2 `wireName` AUTO form). */
function autoSnakeCase(key: string): string {
  return key.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)
}

/** v2 `IMAGE_PARAM_CATALOG[key].wire` overrides — only the irregular spellings. */
const WIRE_NAME_OVERRIDES: Record<string, string> = {
  addWatermark: 'watermark',
  imageResolution: 'size'
}

/** The vendor wire field name for a canonical param (v2 `wireName`). */
export function wireName(key: string): string {
  return WIRE_NAME_OVERRIDES[key] ?? autoSnakeCase(key)
}

/**
 * v2 `normalizeAspectRatio`: the registry stores `ASPECT_16_9`, vendors read `16:9`.
 * Invalid / blank values return `undefined` so the field is omitted entirely.
 */
export function normalizeAspectRatio(value: unknown): string | undefined {
  if (typeof value !== 'string' || value === '') return undefined
  const stripped = value.replace(/^ASPECT_/i, '').replace('_', ':')
  return /^\d+(?:\.\d+)?:\d+(?:\.\d+)?$/.test(stripped) ? stripped : undefined
}

/**
 * v2 `AI_SDK_NATIVE_BINDINGS`: canonical key → the request field the vendor plane
 * consumes, with `aspectRatio` normalized once (v2 does this in `splitParamValues`).
 * `numImages → n` is the only rename.
 */
const NATIVE_BINDINGS: Partial<Record<CanonicalParamKey, { option: string; map?: (value: unknown) => unknown }>> = {
  numImages: { option: 'n' },
  size: { option: 'size' },
  seed: { option: 'seed' },
  aspectRatio: { option: 'aspect_ratio', map: normalizeAspectRatio }
}

/** One profile rule: a literal wire field, a value transform, or a nested block. */
type WireRule =
  | { to: string; map?: (value: unknown, all: Record<string, unknown>) => unknown }
  | { contribute: (value: unknown, all: Record<string, unknown>) => Record<string, unknown> }

/** Per-provider body map — v2 `WireProfile` (+ its `WIRE_REGISTRY` row). */
export interface ImageWireProfile {
  /** Plain fields: forwarded as `wireName(key) → value` (v2 `forward`). */
  readonly forward: readonly CanonicalParamKey[]
  /** Explicit overrides — irregular name / value transform / nested block. */
  readonly fields: Partial<Record<CanonicalParamKey, WireRule>>
  /** Body fields every request carries, `paramValues`-independent (v2 transport). */
  readonly extraBody?: Readonly<Record<string, unknown>>
}

const DIFFUSION_FORWARD: readonly CanonicalParamKey[] = [
  'negativePrompt',
  'seed',
  'numInferenceSteps',
  'guidanceScale',
  'promptEnhancement',
  'quality'
]

const OPENAI_FORWARD: readonly CanonicalParamKey[] = ['quality', 'background', 'moderation', 'style']

/**
 * Registered providers. Every id here is an id the fork can actually serve on this
 * plane; an unlisted provider is refused.
 *
 * NOTE: a profile must forward **every key its models declare** — a declared-but-
 * unforwarded key is exactly the "visible yet silently dropped" defect this port
 * exists to remove. Each profile below is therefore anchored on the catalog's own
 * key surface for its models, not on v2's older per-emitter lists.
 */
export const IMAGE_WIRE_PROFILES: Record<string, ImageWireProfile> = {
  // Catch-all OpenAI-compat diffusion body (v2 DIFFUSION_WIRE_PROFILE) — the
  // `generate_image` tool's provider-less path lands here.
  diffusion: { forward: DIFFUSION_FORWARD, fields: {} },
  // SiliconFlow / z.ai (OpenAI-compat diffusion endpoints).
  silicon: { forward: DIFFUSION_FORWARD, fields: {} },
  zai: { forward: DIFFUSION_FORWARD, fields: {} },
  // ZhiPu (`/api/paas/v4/images/generations`): v2's diffusion body + the two keys
  // its cogview-4 / glm-image catalog blocks declare beyond it (`addWatermark` →
  // `watermark` via the catalog override, `quality`).
  zhipu: { forward: [...DIFFUSION_FORWARD, 'addWatermark', 'quality'], fields: {} },
  // OpenAI image family (v2 OPENAI_WIRE_PROFILE): exactly the four body fields its
  // catalog blocks declare beyond `size`/`n`. `seed` is deliberately NOT forwarded
  // — OpenAI rejects it, matching v2.
  openai: { forward: OPENAI_FORWARD, fields: {} },
  // OpenRouter native `/images` body (v2 OPENROUTER_WIRE_PROFILE).
  openrouter: {
    forward: ['resolution', 'quality', 'outputFormat', 'background'],
    fields: {
      outputCompression: {
        contribute: (value, all) =>
          all.outputFormat === 'jpeg' || all.outputFormat === 'webp' ? { output_compression: value } : {}
      }
    }
  },
  // DMXAPI gateway (v2 DMXAPI_WIRE_PROFILE + the transport's fixed
  // `response_format: 'url'`). Its google `imageConfig` sibling is NOT emitted —
  // that needs `/v1beta/models`, which this plane cannot reach, and the one model
  // declaring `imageResolution` there carries a vendorTransport and is out of scope.
  dmxapi: {
    forward: [...DIFFUSION_FORWARD, 'outputFormat'],
    fields: {
      outputFormat: { to: 'response_format' }
    },
    extraBody: { response_format: 'url' }
  }
}

/** Default profile for an unregistered provider (v2 DEFAULT_DIFFUSION_REGISTRATION). */
export const DEFAULT_IMAGE_WIRE_PROFILE_ID = 'diffusion'

/** The profile for `providerId`, or `undefined` when the provider is off this plane. */
export function resolveImageWireProfile(providerId: string | undefined): ImageWireProfile | undefined {
  if (!providerId) return undefined
  return IMAGE_WIRE_PROFILES[providerId]
}

/**
 * Map a canonical `paramValues` bag to a flat vendor request body.
 *
 * Mirrors v2 `splitParamValues` + `buildImageRequest`:
 *  - blank / `null` / `""` / `"auto"` values are dropped (the byte-identical-wire
 *    invariant, v2 `skipValue`);
 *  - a native binding wins (`numImages → n`, `aspectRatio → aspect_ratio` normalized);
 *  - else the profile field rule (`to` / `contribute`);
 *  - else `wireName(key)` when the key is in the profile's `forward` list;
 *  - anything else is DROPPED, so a vendor is never sent a field its profile does
 *    not declare (v2 behaviour — a profile never got the whole bag).
 */
export function buildImageWireBody(
  profile: ImageWireProfile,
  paramValues: Record<string, unknown>
): Record<string, unknown> {
  const body: Record<string, unknown> = {}

  for (const [key, value] of Object.entries(paramValues)) {
    if (value === undefined || value === '' || value === null || value === 'auto') continue
    const binding = NATIVE_BINDINGS[key as CanonicalParamKey]
    if (binding) {
      const mapped = binding.map ? binding.map(value) : value
      if (mapped !== undefined && mapped !== null && mapped !== '' && mapped !== 'auto') {
        body[binding.option] = mapped
      }
      continue
    }
    const rule = profile.fields[key as CanonicalParamKey]
    if (rule) {
      if ('contribute' in rule) {
        Object.assign(body, rule.contribute(value, paramValues))
      } else {
        body[rule.to] = rule.map ? rule.map(value, paramValues) : value
      }
      continue
    }
    if ((profile.forward as readonly string[]).includes(key)) {
      body[wireName(key)] = value
    }
  }

  return { ...(profile.extraBody ?? {}), ...body }
}

// ── Param bag validation / coercion (fork 缝) ───────────────────────────────
//
// v2 composes a zod schema per (model, mode) in `buildParamsSchema`: the catalog owns
// each key's value type, the per-model `SupportSpec` layers enum/range constraints on
// top, every field is `.catch(undefined)` and the object is `.loose()` so one bad or
// legacy value never fails the whole submit. The fork has no zod on this wire path, so
// the same semantics are implemented directly below — identical observable behaviour:
// blanks → omitted, out-of-constraint → omitted, unknown keys → kept for the caller
// (the legacy-key compatibility path in `canonicalGenerate`).

/** v2 `blankToUndefined`: a blank text input reads as "omitted", never 0/NaN. */
function coerceKind(kind: CanonicalParamKind, value: unknown): unknown {
  if (value === '' || value === null || value === undefined) return undefined
  if (kind === 'string') return typeof value === 'string' ? value : String(value)
  if (kind === 'bool') return typeof value === 'boolean' ? value : undefined
  const numeric = typeof value === 'number' ? value : Number(value)
  if (!Number.isFinite(numeric)) return undefined
  return kind === 'int' ? Math.trunc(numeric) : numeric
}

/** v2 `resolveModeSupports`: the requested mode, else the model's first mode. */
function resolveModeSupports(
  support: ImageGenerationSupport | undefined,
  mode: ImageGenerationMode
): Partial<Record<CanonicalParamKey, SupportSpec>> | undefined {
  const modes = support?.modes
  if (!modes) return undefined
  const fallback = MODE_ORDER.find((candidate) => modes[candidate])
  return (modes[mode] ?? (fallback ? modes[fallback] : undefined))?.supports
}

/** v2 `applyConstraints`: enum options / range bounds, `custom` always allowed. */
function satisfiesConstraints(value: unknown, spec: SupportSpec): boolean {
  if (spec.type === 'enum') {
    return value == null || value === 'custom' || spec.options.includes(String(value))
  }
  if (spec.type === 'range') {
    const numeric = Number(value)
    return value == null || (Number.isFinite(numeric) && numeric >= spec.min && numeric <= spec.max)
  }
  return true
}

/**
 * Validate + coerce a raw form-params bag against a model's support block — the fork
 * equivalent of v2 `buildParamsSchema(support, mode).safeParse(params)`.
 *
 * Returns a bag containing every canonical key (omitted when blank / invalid) plus
 * untouched non-canonical keys, so a legacy or vendor-specific entry survives and the
 * caller decides what to do with it (v2 `.loose()` + `buildParamsSchema`'s `.catch`).
 */
export function buildParamsSchema(
  support: ImageGenerationSupport | undefined,
  mode: ImageGenerationMode = 'generate'
): (params: Record<string, unknown>) => Record<string, unknown> {
  const supports = resolveModeSupports(support, mode)
  return (params) => {
    const out: Record<string, unknown> = {}
    for (const [key, raw] of Object.entries(params)) {
      const canonical = (CANONICAL_PARAM_KEYS as readonly string[]).includes(key)
      if (!canonical) {
        out[key] = raw
        continue
      }
      const coerced = coerceKind(CANONICAL_PARAM_KINDS[key as CanonicalParamKey], raw)
      if (coerced === undefined) continue
      const spec = supports?.[key as CanonicalParamKey]
      if (spec && !satisfiesConstraints(coerced, spec)) continue
      out[key] = coerced
    }
    return out
  }
}
